Versioninfo tool
tianocore/edk2-pytool-extensions pull request #214
Opened 2020-08-28 19:00 UTC by gatys

Adds tool to generate resource file from a JSON representation of version information.

2020-09-11 16:25 UTC, spbrogan commented
Just to update this PR to match our discussion
Todo:

- [ ] Add template step to yaml to allow user of template to insert a step.  Just like the edk2 platform build template file
- [ ] Add step to ubuntu yaml file to install resource compiler using templated step.  See Edk2 ArmVirtPkg/platformci yaml file for example
- [ ] Add tests back for linux that require resource compiler

2020-09-12 00:42 UTC, spbrogan commented on azure-pipelines/templates/basic-setup-steps.yml
> +- name: windres_install
i would change this to extra_steps or caller_steps or something like that.

2020-09-12 00:51 UTC, spbrogan commented on azure-pipelines/templates/basic-setup-steps.yml
> +- name: windres_install
actually this should be moved up one template

2020-09-16 18:31 UTC, matthewfcarlson requested changes

2020-10-14 20:50 UTC, spbrogan requested changes

2020-10-14 20:50 UTC, spbrogan commented on azure-pipelines/ubuntu-test-pr-ci.yml
> +    codecov_enabled: true
this should get reverted

2020-10-14 20:50 UTC, spbrogan commented on setup.py
> +        'pefile>=2019.4.18'
this should probably make a change to y in our version xx.yy.zz

2020-10-15 01:44 UTC, matthewfcarlson approved these changes

2020-10-15 06:34 UTC, spbrogan requested changes

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +import sys
should not have sys

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +FILE_OS_STRINGS = {
I had asked Garand to document some of where this came from.  I believe in a PR he has references to spec, etc.  

I think this file needs some documentation.

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +            print("Could not find VS_FIXEDFILEINFO", file=sys.stderr)
we shouldn't be printing.  Use logging. This will also remove the need for sys.

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +obj = PEObject("C:\\TEMP\\PciBusDxe.efi")
This shouldn't be here.  This looks like test code that will screw up imports.

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +import pefile
basic header, copyright, license, etc

2020-10-15 06:34 UTC, spbrogan commented on edk2toolext/SBAT/PEObject.py
> +    def getVersionJSON(self):
some docstrings maybe?

2020-10-15 06:45 UTC, spbrogan commented on edk2toolext/tests/test_versioninfo.py
> +# @file versioninfo_tool_test.py
incorrect comment

2020-10-15 06:45 UTC, spbrogan commented on edk2toolext/tests/test_versioninfo.py
> +# spell-checker:ignore nmake, UCRT
these words are not in this file anymore

2020-10-16 02:48 UTC, spbrogan approved these changes

2020-10-16 20:38 UTC, merged