Add local file system ext_deps
tianocore/edk2-pytool-extensions pull request #257
Opened 2021-06-27 08:44 UTC by BobCF

Signed-off-by: Bob Feng <bob.c.feng@intel.com>

2021-06-30 05:44 UTC, corthon requested changes

2021-06-30 05:44 UTC, corthon commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +    def checksum(self):
Actually, this could just be a "hash file list" function and be used for both the source_files comparison and the dest_files comparision.

2021-07-12 14:54 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +              "version": "1234",
Yes. I will update the patch and use the AA.BB.CC.DD[-tag]  version format.

2021-07-12 14:55 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +               SHA-1: f31848b6dbaa736aff006bab36243a86c26ea1af
OK. I'll use sha256. Thanks.

2021-07-12 14:58 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +              "OS": "win",
Could you show me an example?

2021-07-12 15:00 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +        for f in self.source_filelist:
Yes. I'll update this implementation. Thanks.

2021-07-12 15:00 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +            yaml.dump({ 'filelist': self.dest_filelist,'SHA-1': self.deps_hash}, file)
Yes.

2021-07-12 15:02 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +        return self.source_filelist, self.deps_hash
OK.

2021-07-12 15:02 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +        for i in range(len(self.source_filelist)):
I'll try to change this to list comprehension.

2021-07-12 15:03 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +    def checksum(self):
OK.

2021-07-12 15:04 UTC, BobCF commented on edk2toolext/environment/extdeptypes/localfile_dependency.py
> +                conf = contents[0]
I'll try to work out a better way to handle non-specific matches.

2022-01-28 19:38 UTC, spbrogan commented
I don't see how this helps provide a consistent and repeatable dev build/env setup.  I think we agreed to close this as deferring out to a local resource is not reliable.   Will close if there is no more feedback.

2022-08-24 20:01 UTC, closed without merging